#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#fondo de pantalla
feh --bg-fill ~/Downloads/wallpaper/d.png

bspc monitor -d I II III IV V VI VII VIII IX 

bspc config border_width         2
bspc config window_gap          10

bspc config focused_border_color "#00ffdd"
bspc config normal_border_color "#000000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manageoff

#polybar
~/.config/polybar/launch.sh 2>/dev/null
echo '' > ~/.config/bin/target #elimina el contenido en la barra target

#compositor de trnasperencias alternativo a picom este xcompmgr
pgrep -x xcompmgr > /dev/null || xcompmgr &

